# Generated by Django 5.1.6 on 2025-02-20 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pavaman_backend', '0002_productdetails_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRegisterDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_no', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(default=1)),
                ('register_status', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('verification_link', models.CharField(blank=True, max_length=255, null=True)),
                ('account_status', models.IntegerField(default=0)),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('otp_send_type', models.CharField(blank=True, max_length=255, null=True)),
                ('reset_link', models.CharField(blank=True, max_length=255, null=True)),
                ('changed_on', models.DateTimeField(blank=True, null=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pavaman_backend.pavamanadmindetails')),
            ],
        ),
    ]
