# Generated by Django 5.1.6 on 2025-02-20 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pavaman_backend', '0004_productdetails_cart_status_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='cart_status',
        ),
    ]
