# Generated by Django 5.1.6 on 2025-02-07 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PavamanAdminDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField()),
                ('category_image', models.CharField(max_length=120)),
                ('category_status', models.IntegerField(default=1)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pavaman_backend.pavamanadmindetails')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField()),
                ('sub_category_image', models.CharField(blank=True, max_length=120, null=True)),
                ('sub_category_status', models.IntegerField(default=1)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pavaman_backend.pavamanadmindetails')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pavaman_backend.categorydetails')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('sku_number', models.CharField(max_length=100, unique=True)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField(default=0)),
                ('discount', models.FloatField(default=0.0)),
                ('material_file', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('number_of_specifications', models.IntegerField(default=0)),
                ('specifications', models.JSONField(blank=True, null=True)),
                ('product_images', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('status', models.IntegerField(default=1)),
                ('availability', models.CharField(default='in_stock', max_length=50)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pavaman_backend.pavamanadmindetails')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pavaman_backend.categorydetails')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pavaman_backend.subcategorydetails')),
            ],
        ),
    ]
