# Generated by Django 5.1.6 on 2025-02-22 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pavaman_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRegisterDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_no', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(default=1)),
                ('register_status', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('verification_link', models.CharField(blank=True, max_length=255, null=True)),
                ('account_status', models.IntegerField(default=0)),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('otp_send_type', models.CharField(blank=True, max_length=255, null=True)),
                ('reset_link', models.CharField(blank=True, max_length=255, null=True)),
                ('changed_on', models.DateTimeField(blank=True, null=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pavaman_backend.pavamanadmindetails')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('sku_number', models.CharField(max_length=100, unique=True)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField(default=0)),
                ('discount', models.FloatField(default=0.0)),
                ('material_file', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('number_of_specifications', models.IntegerField(default=0)),
                ('specifications', models.JSONField(blank=True, null=True)),
                ('product_images', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('status', models.IntegerField(default=1)),
                ('availability', models.CharField(default='in_stock', max_length=50)),
                ('product_status', models.IntegerField(default=1)),
                ('cart_status', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pavaman_backend.pavamanadmindetails')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pavaman_backend.categorydetails')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pavaman_backend.subcategorydetails')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductDetails',
        ),
    ]
