# Generated by Django 5.1.6 on 2025-02-22 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pavaman_backend', '0002_customerregisterdetails_productsdetails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pavaman_backend.categorydetails')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pavaman_backend.customerregisterdetails')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pavaman_backend.productsdetails')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pavaman_backend.subcategorydetails')),
            ],
        ),
    ]
