# Generated by Django 5.1.6 on 2025-02-28 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pavaman_backend', '0003_cartproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=15)),
                ('alternate_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('address_type', models.CharField(choices=[('home', 'Home'), ('work', 'Work')], default='home', max_length=10)),
                ('pincode', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=255)),
                ('village', models.CharField(max_length=255)),
                ('mandal', models.CharField(blank=True, max_length=255, null=True)),
                ('postoffice', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='pavaman_backend.customerregisterdetails')),
            ],
        ),
    ]
