# Generated by Django 5.1.6 on 2025-02-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pavaman_backend', '0004_customeraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='landmark',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='village',
            field=models.CharField(default='', max_length=255),
        ),
    ]
