# Generated by Django 5.1.6 on 2025-02-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pavaman_backend', '0005_customeraddress_district_customeraddress_landmark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='district',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='village',
            field=models.CharField(max_length=255),
        ),
    ]
