# Generated by Django 5.1.6 on 2025-03-01 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pavaman_backend', '0006_alter_customeraddress_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='latitude',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='longitude',
            field=models.CharField(default='', max_length=100),
        ),
    ]
