# Generated by Django 5.1.6 on 2025-03-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pavaman_backend', '0007_customeraddress_latitude_customeraddress_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsdetails',
            name='product_url_id',
            field=models.CharField(default=''),
        ),
    ]
