# Generated by Django 5.1.6 on 2025-03-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pavaman_backend', '0008_productsdetails_product_url_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorydetails',
            name='category_url_id',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='subcategorydetails',
            name='sub_category_url_id',
            field=models.CharField(default=''),
        ),
    ]
