# Generated by Django 5.1.6 on 2025-03-03 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pavaman_backend', '0009_categorydetails_category_url_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorydetails',
            name='category_url_id',
        ),
    ]
