# Generated by Django 5.1.6 on 2025-03-03 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pavaman_backend', '0010_remove_categorydetails_category_url_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsdetails',
            name='product_url_id',
        ),
        migrations.RemoveField(
            model_name='subcategorydetails',
            name='sub_category_url_id',
        ),
    ]
