# Generated by Django 5.1.5 on 2025-03-27 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pavaman_backend', '0011_remove_productsdetails_product_url_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproducts',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pavaman_backend.pavamanadmindetails'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('sub_category', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_status', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField()),
                ('admin', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pavaman_backend.pavamanadmindetails')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pavaman_backend.customerregisterdetails')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pavaman_backend.productsdetails')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(max_length=255, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=20)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card')], default='cash', max_length=40)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pavaman_backend.pavamanadmindetails')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pavaman_backend.categorydetails')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pavaman_backend.customerregisterdetails')),
                ('customer_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pavaman_backend.customeraddress')),
                ('order_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pavaman_backend.orderproducts')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pavaman_backend.productsdetails')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pavaman_backend.subcategorydetails')),
            ],
        ),
    ]
