# Generated by Django 5.1.6 on 2025-02-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pavaman_backend', '0003_remove_productdetails_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='product_status',
            field=models.IntegerField(default=1),
        ),
    ]
