# Generated by Django 5.1.6 on 2025-02-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pavaman_backend', '0004_productdetails_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='cart_status',
            field=models.BooleanField(default=False),
        ),
    ]
