# Generated by Django 5.1.6 on 2025-02-22 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pavaman_backend', '0003_cartproducts'),
        ('pavaman_backend', '0005_productdetails_cart_status'),
    ]

    operations = [
    ]
